/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MailboxDynamic } from './MailboxDynamic';
export * as factories from './factories';
export { MailboxDynamic__factory } from './factories/MailboxDynamic__factory';
