/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MailboxDataInterface extends Interface {
  getFunction(nameOrSignature: "sendData"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MessageData"): EventFragment;

  encodeFunctionData(
    functionFragment: "sendData",
    values: [AddressLike, string]
  ): string;

  decodeFunctionResult(functionFragment: "sendData", data: BytesLike): Result;
}

export namespace MessageDataEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike, data: string];
  export type OutputTuple = [from: string, to: string, data: string];
  export interface OutputObject {
    from: string;
    to: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MailboxData extends BaseContract {
  connect(runner?: ContractRunner | null): MailboxData;
  waitForDeployment(): Promise<this>;

  interface: MailboxDataInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  sendData: TypedContractMethod<
    [to: AddressLike, data: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "sendData"
  ): TypedContractMethod<[to: AddressLike, data: string], [void], "nonpayable">;

  getEvent(
    key: "MessageData"
  ): TypedContractEvent<
    MessageDataEvent.InputTuple,
    MessageDataEvent.OutputTuple,
    MessageDataEvent.OutputObject
  >;

  filters: {
    "MessageData(address,address,string)": TypedContractEvent<
      MessageDataEvent.InputTuple,
      MessageDataEvent.OutputTuple,
      MessageDataEvent.OutputObject
    >;
    MessageData: TypedContractEvent<
      MessageDataEvent.InputTuple,
      MessageDataEvent.OutputTuple,
      MessageDataEvent.OutputObject
    >;
  };
}
