/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { MailboxData, MailboxDataInterface } from "../MailboxData";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "data",
        type: "string",
      },
    ],
    name: "MessageData",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "string",
        name: "data",
        type: "string",
      },
    ],
    name: "sendData",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b5061029d806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063e6dd938d14610030575b600080fd5b61004a60048036038101906100459190610185565b61004c565b005b8273ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff167fa999d80781c2f53212c33e116dd83f50dc4f7a213f304e36bab3e4e08034da2584846040516100ab929190610243565b60405180910390a3505050565b600080fd5b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006100ed826100c2565b9050919050565b6100fd816100e2565b811461010857600080fd5b50565b60008135905061011a816100f4565b92915050565b600080fd5b600080fd5b600080fd5b60008083601f84011261014557610144610120565b5b8235905067ffffffffffffffff81111561016257610161610125565b5b60208301915083600182028301111561017e5761017d61012a565b5b9250929050565b60008060006040848603121561019e5761019d6100b8565b5b60006101ac8682870161010b565b935050602084013567ffffffffffffffff8111156101cd576101cc6100bd565b5b6101d98682870161012f565b92509250509250925092565b600082825260208201905092915050565b82818337600083830152505050565b6000601f19601f8301169050919050565b600061022283856101e5565b935061022f8385846101f6565b61023883610205565b840190509392505050565b6000602082019050818103600083015261025e818486610216565b9050939250505056fea2646970667358221220c5b6bf0aa81883d98ee59aa6896175c396c41a39ab727f280e6ac26c0ed454a064736f6c63430008140033";

type MailboxDataConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MailboxDataConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MailboxData__factory extends ContractFactory {
  constructor(...args: MailboxDataConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MailboxData & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MailboxData__factory {
    return super.connect(runner) as MailboxData__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MailboxDataInterface {
    return new Interface(_abi) as MailboxDataInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MailboxData {
    return new Contract(address, _abi, runner) as unknown as MailboxData;
  }
}
