/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { Mailbox, MailboxInterface } from "../Mailbox";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "payloadHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "cid",
        type: "string",
      },
    ],
    name: "Message",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "bytes32",
        name: "payloadHash",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "cid",
        type: "string",
      },
    ],
    name: "send",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610307806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063f47120a814610030575b600080fd5b61004a600480360381019061004591906101be565b61004c565b005b8373ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff167f44d70b243fb52c67a4289349755e0dbe7a5c6b6ecbe6f766b96ec34aee0d0ba98585856040516100ad9392919061029f565b60405180910390a350505050565b600080fd5b600080fd5b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006100f0826100c5565b9050919050565b610100816100e5565b811461010b57600080fd5b50565b60008135905061011d816100f7565b92915050565b6000819050919050565b61013681610123565b811461014157600080fd5b50565b6000813590506101538161012d565b92915050565b600080fd5b600080fd5b600080fd5b60008083601f84011261017e5761017d610159565b5b8235905067ffffffffffffffff81111561019b5761019a61015e565b5b6020830191508360018202830111156101b7576101b6610163565b5b9250929050565b600080600080606085870312156101d8576101d76100bb565b5b60006101e68782880161010e565b94505060206101f787828801610144565b935050604085013567ffffffffffffffff811115610218576102176100c0565b5b61022487828801610168565b925092505092959194509250565b61023b81610123565b82525050565b600082825260208201905092915050565b82818337600083830152505050565b6000601f19601f8301169050919050565b600061027e8385610241565b935061028b838584610252565b61029483610261565b840190509392505050565b60006040820190506102b46000830186610232565b81810360208301526102c7818486610272565b905094935050505056fea26469706673582212204dfe379c66f1c105f4eb924c3265cc1504619de65f4138f50c9ed1a347d44e8764736f6c63430008140033";

type MailboxConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MailboxConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Mailbox__factory extends ContractFactory {
  constructor(...args: MailboxConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Mailbox & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Mailbox__factory {
    return super.connect(runner) as Mailbox__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MailboxInterface {
    return new Interface(_abi) as MailboxInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): Mailbox {
    return new Contract(address, _abi, runner) as unknown as Mailbox;
  }
}
